channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - defaults::python=3.12
  - conda-forge::sqlite
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - conda-forge::libjpeg-turbo
