channels:
  - conda-forge
  - pytorch
dependencies:
  - conda-forge::python=3.12
  - conda-forge::sqlite
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - conda-forge::libjpeg-turbo
